# Generated by Django 5.1.3 on 2025-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=20)),
                ('produto', models.CharField(max_length=255)),
                ('st_difal', models.CharField(max_length=10)),
                ('aquisicao', models.CharField(max_length=10)),
                ('origem', models.CharField(max_length=20)),
                ('st_inclusa', models.CharField(max_length=10)),
                ('origem_importada', models.FloatField(default=0)),
                ('origem_nacional', models.FloatField(default=0)),
                ('origem_rj', models.FloatField(default=0)),
                ('reducao', models.CharField(default='NÃO', max_length=3)),
                ('valor_reducao', models.FloatField(default=0)),
            ],
        ),
    ]
